language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcppunit-dev
  - sudo pip install cpp-coveralls --use-mirrors
script:
  - make all check
after_success:
  - test $CC = gcc && find out/testUnits.d/ -name '*.o' | while read f; do gcov -p -o $f $f; done
  - test $CC = gcc && coveralls --no-gcov --build-root "${PWD}" --exclude tests/
